name = "multimedia"
main = "worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
TTS_REFERENCE_ID = "8d21b053e2804e2a890e1cf62f267b6f"
TTS_MODEL = "s2.1-pro-free"
